
/*Adiciona a coluna para verificar se o perfil do usuário permite acessar o menu de relatórios*/
alter table USUARIOPERFIL
	add CONSULTAR_RELATORIO varchar(1)
go

alter table BKPUSUARIOPERFIL
	add CONSULTAR_RELATORIO varchar(1)
go

alter view VUSUARIOPERFIL as SELECT UP_CODIGO
  ,UP_NOME
  ,UP_D01,UP_D02,UP_D03,UP_D04,UP_D05,UP_D06,UP_D07,UP_D08,UP_D09,UP_D10
  ,UP_D11,UP_D12,UP_D13,UP_D14,UP_D15,UP_D16,UP_D17,UP_D18,UP_D19,UP_D20
  ,UP_ATIVO,UP_REG,UP_CODUSR, CONSULTAR_RELATORIO
FROM USUARIOPERFIL
go

CREATE TABLE CONSOLIDACAO_INFRACAO
(
	COD_CONSOLIDACAO int identity
		constraint CONSOLIDACAO_INFRACAO_pk
			primary key nonclustered,
	DATA_CONSOLIDACAO datetime not null,
	ULTIMA_POSICAO_MOVIMENTO bigint not null,
	REGISTROS_IMPORTADOS int not null
)
go

CREATE TABLE INFRACAO
(
	ID int identity
		constraint INFRACAO_pk
			primary key nonclustered,
	PLACA VARCHAR(10) NOT NULL,
	FROTA VARCHAR(1) NOT NULL,
	TURNO VARCHAR(1) NOT NULL,
	POSICAO_INICIAL BIGINT NOT NULL,
	DATA_INICIAL DATETIME NOT NULL,
	POSICAO_FINAL BIGINT,
	DATA_FINAL DATETIME,
	TEMPO VARCHAR(10),
	VELOCIDADE INT NOT NULL,
	VELOCIDADE_MAX INT NOT NULL,
	CODIGO_MOTORISTA INT NOT NULL,
	CODIGO_UNIDADE INT NOT NULL,
	DESCALIBRADO VARCHAR(5) NOT NULL,
	CODIGO_EVENTO INT NOT NULL,
	RFID VARCHAR(30) NOT NULL,
	DISTANCIA_PERCORRIDA NUMERIC(15,4),
	ANO_MES INT NOT NULL,
	ERRO
)
go